tmpfiles = *.bbl CCNUthesis-main.bib.blg CCNUthesis-main.blg  main.bcf main.blg main.fdb_* main.fls main.lof main.lot main.toc main.aux main.out main.xdv main.synctex.gz main.run.xml main.tex.b*

clean:
	rm -rf $(tmpfiles)
